
version: "3.1"
services:

    docker-redis:
      image: redis:alpine
      container_name: eshop-redis
      networks:
        - eshop-net

    docker-mariadb:
      image: mariadb:10.4
      container_name: eshop-mariadb
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/mysql:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=eshopdb
        - MYSQL_USER=eshop_user
        - MYSQL_PASSWORD=eshop_user_password
      ports:
        - "5052:3306"
      networks:
        - eshop-net


    app:
      build:
        args:
          user: project_user
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      container_name: eshop-app
      working_dir: /application
      volumes:
        - ./:/application
      networks:
        - eshop-net


    webserver:
      image: nginx:alpine
      container_name: eshop-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "5050:80"
      networks:
        - eshop-net
    phpmyadmin:
      depends_on:
        - docker-mariadb
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '5056:80'
      environment:
        - PMA_HOST=docker-mariadb
        - MYSQL_ROOT_PASSWORD=root
        - UPLOAD_LIMIT=900M
      networks:
        - eshop-net


networks:
  eshop-net:
    driver: bridge
